### ISSUE TITLE
Making the navbar more clean and organized using bootstrap css

### ISSUE THREAD

**Issue by Sch476** [akshitagupta15june/Moksh#257]
I would like to make the navbar of the "Moksh" website more clean and organized.

Please assign this work to me.
GSSOC'23 contributor 

![Screenshot (97)](https://github.com/akshitagupta15june/Moksh/assets/127319225/55d7387a-9f02-4eff-80c2-cc8f6ce647de)

**Comment by PrathamAsrani** [comment]
Respected Repo Owners & Managers,

Problems seen in Website Background: 
1.	The image added is overlaying with the width of overall website, due to which the extra right column white space is present in the respective website.
2.	The components of the navbar are sized in pixel due to which the site looks uneven.

Solution: 
1.	Is ‘me’ please assign me for the navbar + background modification

<img width="500" alt="Extra Spaced Column" src="https://github.com/akshitagupta15june/Moksh/assets/114286503/baa53e73-3ace-4412-bd7e-86932dc0d8c7">
<img width="220" alt="NavbarProblem" src="https://github.com/akshitagupta15june/Moksh/assets/114286503/de5a62a7-9ac4-41a5-ac21-688ba1ad389b">


Note: I have added the images with red color text in it showing the problem.
E: prathamasrani.cs@gmail.com
M: +91 91454 95032

**Comment by VamilP** [comment]
Hi Team,

Good Day!

I have made changes to the code and created a responsive navbar. This was achieved by taking the below steps. 

1. Made the navbar more clean
2. Made it responsive

Kindly find the attached snapshots of the updates done by me.

<img width="947" alt="update-responsive-navbar-desktop-view" src="https://github.com/akshitagupta15june/Moksh/assets/89695376/de26f78d-7ef0-4002-afdf-14e0f70cb324">
<img width="339" alt="update-responsive-navbar-mobile-view" src="https://github.com/akshitagupta15june/Moksh/assets/89695376/4f6fd039-7ca9-4873-b132-fbdc09d809ec">
<img width="334" alt="update-responsive-navbar-mobile-view-menu" src="https://github.com/akshitagupta15june/Moksh/assets/89695376/4a1e1b23-b23a-40ff-9355-eb8730b48cee">


I would request you to assign me this task so that I can raise the pull request for the same.


GSSOC'23 contributor

**Comment by akshitagupta15june** [comment]
some are working on this
