### ISSUE TITLE
Modifying the background in home page

### ISSUE THREAD

**Issue by sanchitaa14** [akshitagupta15june/Moksh#259]
GSSoC'23
The background looks plain, and since the site takes up a sensitive issue it should look simple and modest rather than childish

**Comment by PrathamAsrani** [comment]
Respected Repo Owners & Managers,

Problems seen in Website Background: 
1.	The image added is overlaying with the width of overall website, due to which the extra right column white space is present in the respective website.
2.	The components of the navbar are sized in pixel due to which the site looks uneven.

Solution: 
1.	Is ‘me’ please assign me for the navbar + background modification

<img width="500" alt="Extra Spaced Column" src="https://github.com/akshitagupta15june/Moksh/assets/114286503/baa53e73-3ace-4412-bd7e-86932dc0d8c7">
<img width="220" alt="NavbarProblem" src="https://github.com/akshitagupta15june/Moksh/assets/114286503/de5a62a7-9ac4-41a5-ac21-688ba1ad389b">


Note: I have added the images with red color text in it showing the problem.
E: prathamasrani.cs@gmail.com
M: +91 91454 95032

**Comment by akshitagupta15june** [comment]
some are working on this
