### ISSUE TITLE
You can create new issues, report bugs and improve UI or even start with documentation of readme

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/Moksh#3]
This website has been created solely using HTML, CSS, and JavaScript, making it an excellent platform for beginners to contribute to a noble cause.
You can always take help of ISKCON Vedabase library https://vedabase.io/

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by yuvraj6446** [comment]
- This site is not responsive at all. Many items' , dimensions are hard coded.
- We should work over it's responsiveness so that it can work on different devices .
- We should work over it's navbar so that it will become more user friendly( we can add hover effects, improvement in the positioning of navbar elements, add scaling effects, once the element is selected it's appearance will be changed.
- Bug:- In features section rejuvenate. We have to resolve these bugs for better flow.
- kindly assign me this task.

**Comment by Pragati-3003** [comment]
Hey @akshitagupta15june , 
I would like to contribute on this .
Please assign this issue to me under GSSOC'23.
Thanks
