### ISSUE TITLE
Development of Backend and Admin Panel

### ISSUE THREAD

**Issue by parth782** [akshitagupta15june/Moksh#628]
## Description
 I have noticed that website is static I will make this website dynamic by adding **Admin Panel** .  

**Is your feature request related to a problem? Please describe.**
Yes , this functionality will ease the website owner to add events through UI and moreover we can add backend in the website. We can control flow of events in the website and we can also add blogging functionality in this website.

**Describe the solution you'd like**
I will  develop Admin Panel and make whole website dynamic. I will also add functionality of blogging and events control with registration and automatic email system for event registration.
TechStack : -

**NodeJS , ExpressJS , EJS.**

@akshitagupta15june Kindly assign this feature to me under **GSSOC23**

**Comment by ankitjt** [comment]
The project is mostly targeted towards beginners that's why it's made using html css and js. 
As of now there is no immediate plan to add any back end functionality or to use any progressive frameworks like react for the project. 

Please visit the repository from time to time if we decide to go in that direction you can raise an issue. 

Closing the issue for now.
