### ISSUE TITLE
<Improve UI>The UI could be improved

### ISSUE THREAD

**Issue by jayk-gupta** [akshitagupta15june/Moksh#66]
The following things could be improved:
- Color scheme
- Font
- Layout 
Can I work on these?

**Comment by akshitagupta15june** [comment]
which ui that you want to improve like of index page?

**Comment by ankitjt** [comment]
@jayk-gupta currently the framework for CSS is Bootstrap. You can refer to [Bootstrap](https://getbootstrap.com/docs/5.3/getting-started/introduction/) documentation for reference and if you have any questions related to it you can ask in our discord's 'ask-doubts' channel.

Let us know if you are still working on the issue so we can keep it open otherwise we'll close it. @akshitagupta15june
