### ISSUE TITLE
design a Contact us page 

### ISSUE THREAD

**Issue by bhaskarkumar1** [akshitagupta15june/Moksh#667]
I want to design a contact us page.  So please assign me this task so that I can work on it.

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I will create a contact us page

**Comment by ankitjt** [comment]
Duplicate #604

**Comment by bhaskarkumar1** [comment]
sir, but  it is not assigned to any contributor, you can check.

**Comment by ankitjt** [comment]
Yes, I could see that it is not yet assigned.

As there are lot of issues, screening them all for duplicates and then assigning them is taking a bit time. Since similar issue was raised before yours it was flagged as duplicate.
All issues are on first come basis.

You can wait or check for other bugs/features to contribute.
